title: Alex Ross Study Blog
email: ross@rosslopez.rocks

description: >- # this means to ignore newlines until "baseurl:"
  Writing about my experiences in Coding, Programming Interview questions and the explanations on the answers I came up with.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.rosslopez.rocks" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: _lexRoss
github_username:  alex-ross83

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
